en_example_json: "/root/NetAutoTest/data/rewrite_results/all_python_results_english.json"  # 英文版示例改写库
zh_example_json: "/root/NetAutoTest/data/rewrite_results/all_python_results_chinese.json"  # 中文版示例改写库
language: en
top_k: 3


model: "deepseek-r1"
api_key: "sk-e025fbab2599423fb0946f3acb9bdda6"
base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

retriever:
  use_local: true
  local_model: "paraphrase-multilingual-MiniLM-L12-v2"

  use_remote: false
  remote_base_url: "https://your-api.com/retrieve"
  remote_api_key: "your-api-key"

  use_rerank: true
  rerank_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
